<?php
/**
 * @file
 * logancee_search.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function logancee_search_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_language_en_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_language_en_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_language_it_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_language_it_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_language_pt-br_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_language_pt-br_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_language_und_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_language_und_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_article_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_article_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_blog_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_blog_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_clients_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_clients_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_fluid2_slider_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_fluid2_slider_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_fluid_boxes_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_fluid_boxes_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_fluid_slider_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_fluid_slider_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_front_carousel_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_front_carousel_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_front_main_slider2_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_front_main_slider2_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_front_main_slider_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_front_main_slider_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_multiscroll_item_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_multiscroll_item_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_page_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_page_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_parallax_item_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_parallax_item_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_advanced_type_product_display_display';
  $strongarm->value = 1;
  $export['custom_search_advanced_type_product_display_display'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_i18n_search_language';
  $strongarm->value = 'current';
  $export['custom_search_i18n_search_language'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_node_types_excluded';
  $strongarm->value = array(
    'article' => 'article',
    'page' => 'page',
    'clients' => 'clients',
    'fluid_boxes' => 'fluid_boxes',
    'fluid_slider' => 'fluid_slider',
    'front_carousel' => 'front_carousel',
    'front_main_slider' => 'front_main_slider',
    'front_main_slider2' => 'front_main_slider2',
    'multiscroll_item' => 'multiscroll_item',
    'parallax_item' => 'parallax_item',
    'fluid2_slider' => 'fluid2_slider',
    'blog' => 0,
    'product_display' => 0,
  );
  $export['custom_search_node_types_excluded'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_results_info_comment';
  $strongarm->value = 0;
  $export['custom_search_results_info_comment'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_results_info_date';
  $strongarm->value = 1;
  $export['custom_search_results_info_date'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_results_info_type';
  $strongarm->value = 1;
  $export['custom_search_results_info_type'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'custom_search_results_info_user';
  $strongarm->value = 0;
  $export['custom_search_results_info_user'] = $strongarm;

  return $export;
}
